# Generated by Django 4.2.4 on 2023-10-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_imagem', models.ImageField(upload_to='imagems/produtos')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('BOLOS', 'Bolos'), ('CATEGORIA 2', 'Categoria 2'), ('CATEGORIA 3', 'Categoria 3')], max_length=50)),
                ('preco', models.FloatField(default=1.0)),
            ],
        ),
    ]
