# Generated by Django 4.2.4 on 2024-10-25 18:08

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_imagem', models.ImageField(upload_to='produtos')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('APARELHOS', 'Aparelhos'), ('ROUPAS', 'Roupas')], max_length=50)),
                ('quantidade', models.IntegerField(validators=[products.models.validar_quantidade])),
                ('preco', models.FloatField(default=1.0)),
            ],
        ),
    ]
