# Generated by Django 4.2.4 on 2023-10-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(choices=[('APARELHOS', 'Aparelhos'), ('ROUPAS', 'Roupas')], max_length=50),
        ),
    ]
