# Generated by Django 4.2.4 on 2025-01-29 15:02

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.FloatField(default=1.0, validators=[products.models.validar_preco]),
        ),
    ]
