# Generated by Django 4.2.4 on 2025-01-29 15:30

from decimal import Decimal
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_produtos_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[products.models.validar_preco]),
        ),
    ]
