# Generated by Django 4.2.4 on 2025-01-29 16:33

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produtos_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[products.models.validar_preco]),
        ),
    ]
