# Generated by Django 4.2.4 on 2024-10-19 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pedido', models.CharField(max_length=50)),
                ('preco', models.FloatField()),
                ('email', models.EmailField(max_length=255)),
                ('entrega_status', models.CharField(choices=[('PREPARANDO...', 'Preparando...'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue')], default='PREPARANDO...', max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
