# Generated by Django 4.2.4 on 2023-08-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pedido', models.CharField(max_length=50)),
                ('preco', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('entrega_status', models.CharField(choices=[('PREPARANDO...', 'Preparando...'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue')], default='PREPARANDO...', max_length=20)),
            ],
        ),
    ]
